## What is numpy ?
Numpy is multidimensional array library.
* Faster to read less bytes of memory.
* No type checking when iterating through objects.

## Applications of Numpy 
* Mathematics (MATLAB Replacement)
* Plotting (Matplotlib)
* Backend (Pandas , Connect 4 , Digital Photography)
* Machine Learning





**Load in Numpy**

In [2]:
import numpy as np

**The Basics**

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#get dimension
a.ndim

1

In [6]:
#get shape
a.shape

(3,)

In [7]:
#get type
a.dtype

dtype('int32')

In [8]:
#get size
a.itemsize

4

In [9]:
#get total size
a.size * a.itemsize

12

**Accessing / Changing specific elements , rows , columns etc**

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
#get specific elements
a[1,5] = 25
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 25 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 25 14]]


In [27]:
#get specific row
a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#get specific columns
a[:,2]

array([ 3, 10])

In [30]:
#getting more [startindex:endindex:stepsize]
a[1, 1:6:2]

array([ 9, 11, 25])

**Intializing different type of arrays**

In [33]:
#All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#All 1's matrix
np.ones((4,2,2,5), dtype='int32')

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [40]:
#Any other value
np.full((2,2),99 , dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [44]:
#Random decimal number
np.random.randint(8,size=((3,3)))

array([[4, 0, 2],
       [3, 7, 1],
       [3, 4, 6]])

In [47]:
#identitybmatrix
np.identity(4 , dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [50]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [57]:
output = np.ones((5,5),dtype='int32')
print(output)

z= np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [61]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


**Mathematics**

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a+2

array([3, 4, 5, 6])

In [64]:
a-2

array([-1,  0,  1,  2])

In [65]:
a*2

array([2, 4, 6, 8])

In [66]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [67]:
a**2

array([ 1,  4,  9, 16])

In [68]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Linear Algebra**

In [75]:
a = np.full((2,3),2)
print(a)

b= np.ones((3,2) , dtype='int32')
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[1 1]
 [1 1]
 [1 1]]


array([[6, 6],
       [6, 6]])

In [78]:
c = np.identity((3),dtype='int32')
np.linalg.det(c)

1.0

**Statistics**

In [84]:
stats= np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [87]:
np.min(stats)

1

In [88]:
np.max(stats)

6

**Miscellaneous**


*Load Data from File*

In [90]:
data = np.genfromtxt('sample.csv',delimiter=',',skip_header=1,dtype='int')
print(data)

[[  1  25 170  70  85]
 [  2  30 160  65  90]
 [  3  22 175  68  78]
 [  4  28 180  75  88]
 [  5  26 165  72  80]]


*Boolean Masking and Advanced Indexing*

In [91]:
data>50

array([[False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [92]:
data[data>50]

array([170,  70,  85, 160,  65,  90, 175,  68,  78, 180,  75,  88, 165,
        72,  80])

In [ ]:
#You can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
